# Generated by Django 5.2.3 on 2025-06-23 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2_ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
