# Generated by Django 5.2.3 on 2025-06-28 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2_ads', '0002_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='wishlist',
        ),
        migrations.AddField(
            model_name='customer',
            name='wishlist',
            field=models.ManyToManyField(null=True, related_name='wishlisted_by', to='app2_ads.ad'),
        ),
    ]
