# Generated by Django 5.2.3 on 2025-07-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2_ads', '0003_remove_customer_wishlist_customer_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='wishlist',
            field=models.ManyToManyField(related_name='wishlisted_by', to='app2_ads.ad'),
        ),
    ]
