# Generated by Django 5.2.3 on 2025-06-23 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2_ads', '0003_alter_seller_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='address',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
