# Generated by Django 5.2.3 on 2025-06-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2_ads', '0004_alter_seller_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
