# Generated by Django 5.2.3 on 2025-07-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2_ads', '0005_alter_customer_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='wishlist',
            field=models.ManyToManyField(blank=True, related_name='wishlist', to='app2_ads.ad'),
        ),
    ]
