# Generated by Django 5.2.3 on 2025-06-28 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<<< HEAD:classifieds/migrations/0003_remove_customer_wishlist_customer_wishlist.py
        ('classifieds', '0002_customer'),
========
        ('user_management', '0002_customer'),
>>>>>>>> 260fb9cf69e02f6c538eae5c14c1c6b8f96d97d5:user_management/migrations/0003_remove_customer_wishlist_customer_wishlist.py
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='wishlist',
        ),
        migrations.AddField(
            model_name='customer',
            name='wishlist',
<<<<<<<< HEAD:classifieds/migrations/0003_remove_customer_wishlist_customer_wishlist.py
            field=models.ManyToManyField(null=True, related_name='wishlisted_by', to='classifieds.ad'),
========
            field=models.ManyToManyField(null=True, related_name='wishlisted_by', to='user_management.ad'),
>>>>>>>> 260fb9cf69e02f6c538eae5c14c1c6b8f96d97d5:user_management/migrations/0003_remove_customer_wishlist_customer_wishlist.py
        ),
    ]
