# Generated by Django 5.2.3 on 2025-07-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<<< HEAD:classifieds/migrations/0004_alter_customer_wishlist.py
        ('classifieds', '0003_remove_customer_wishlist_customer_wishlist'),
========
        ('user_management', '0003_remove_customer_wishlist_customer_wishlist'),
>>>>>>>> 260fb9cf69e02f6c538eae5c14c1c6b8f96d97d5:user_management/migrations/0004_alter_customer_wishlist.py
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='wishlist',
<<<<<<<< HEAD:classifieds/migrations/0004_alter_customer_wishlist.py
            field=models.ManyToManyField(related_name='wishlisted_by', to='classifieds.ad'),
========
            field=models.ManyToManyField(related_name='wishlisted_by', to='user_management.ad'),
>>>>>>>> 260fb9cf69e02f6c538eae5c14c1c6b8f96d97d5:user_management/migrations/0004_alter_customer_wishlist.py
        ),
    ]
