databases:
  - name: easyads_db
    plan: free
    databaseName: easyads_db
    user: easyads_db_user

services:
  - type: web
    plan: free
    name: easyads
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn easyads.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: easyads_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 1
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: easyads.onrender.com
