# Generated by Django 5.0.7 on 2025-06-03 16:06

import app1_users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1_users', '0002_remove_user_username_alter_user_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', app1_users.models.UserManager()),
            ],
        ),
    ]
