# Generated by Django 5.2.3 on 2025-07-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0004_alter_customer_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='wishlist',
            field=models.ManyToManyField(blank=True, related_name='wishlisted_by', to='classifieds.ad'),
        ),
    ]
